apiVersion: apps/v1
kind: Deployment
metadata:
  name: cas-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cas
  template:
    metadata:
      labels:
        app: cas
    spec:
      containers:
        - name: cas
          image: ghcr.io/cas-4/backend:latest
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              valueFrom:
                configMapKeyRef:
                  name: cas-config
                  key: RUST_LOG
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: cas-config
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cas-secret
                  key: JWT_SECRET
            - name: EXPO_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cas-secret
                  key: EXPO_ACCESS_TOKEN
            - name: UNREALSPEECH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cas-secret
                  key: UNREALSPEECH_TOKEN
            - name: ALLOWED_HOST
              valueFrom:
                configMapKeyRef:
                  name: cas-config
                  key: ALLOWED_HOST
          ports:
            - containerPort: 8000
      restartPolicy: Always
