apiVersion: v1
kind: ConfigMap
metadata:
  name: cas-frontend-config
data:
  VITE_API_URL: ${VITE_API_URL}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cas-frontend-deployment
  labels:
    app: cas-frontend-app
spec:
  selector:
    matchLabels:
      app: cas-frontend-app
  template:
    metadata:
      labels:
        app: cas-frontend-app
    spec:
      containers:
        - name: frontend
          image: ghcr.io/cas-4/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: cas-frontend-config
                  key: VITE_API_URL
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cas-frontend-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: cas-frontend-app
  type: NodePort
